name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: 🚀 Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macos-10.15
          - ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Set current repository for pull requests
        run: |
          echo "DOTFILES_PR_REPOSITORY=${{ github.event.pull_request.head.repo.full_name }}" >> $GITHUB_ENV
      - name: Set current repository and branch
        run: |
          echo "DOTFILES_REPOSITORY=${DOTFILES_PR_REPOSITORY:-franciscorzl/dotfiles}" >> $GITHUB_ENV
          echo "DOTFILES_BRANCH=${{ github.head_ref }}" >> $GITHUB_ENV
          echo "DOTFILES_ENV=CI" >> $GITHUB_ENV
      - name: Install
        run: echo "$HOME/.dotfiles" | bash installer

      - name: Debug on error
        if: ${{ failure() }}
        run: |
          echo "DOTFILES_REPOSITORY: $DOTFILES_REPOSITORY"
          echo "DOTFILES_BRANCH: $DOTFILES_BRANCH"
          echo "DOTFILES_ENV: $DOTFILES_ENV"
          cat "$HOME/dotfiles.log"
          
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false
